import type { Metadata } from "next";
import "react-datepicker/dist/react-datepicker.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import "../styles/globals.scss";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Black Jade Fintec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
      <Toaster
        position="top-center"
        duration={4000}
        visibleToasts={3}
        richColors
      />
    </html>
  );
}
